# Generated by Django 5.0 on 2023-12-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="desc",
            field=models.TextField(),
        ),
    ]
